name: "Business Manage System Project Build"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        user: actions/checkout@v2.6.0
        with:
          persist-credentials: false

      - mame: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: imchrisorz
          password: dckr_pat_UUoUPBvOuTi1_RQWsjdbqSUiZOA

      - name: Build Docker Image
        run : |
          bash ./scripts/release.sh